### Environment specific secure properties go here ###
### Secure Properties need to be added in an encrypted fashion. 
### The secure-properties-tool.jar can be downloaded from https://docs.mulesoft.com/downloads/mule-runtime/4.2/secure-properties-tool.jar ###
### The values can be encrypted by running the following command in a command prompt ###
### java -jar secure-properties-tool.jar <method> <operation> <algorithm> <mode> <key> <value> ###
### method is hardcoded to string ###
### operation takes the values encrypt or decrypt ###
### algorithm is the encryption algorithm ###
### mode is the encryption mode ###
### key is the encryption/decryption key ###
### value is the plain text value that needs to encrypted or the encrypted value that needs to be decrypted ###
### Once the value is encrypted it can be added as prop.name=![encryptedValue] where prop.name is the name of your encrypted property ###

#### HTTPS TLS Keystore ####
tls:
  keystore:
    keypassword: "![+yDkiDGqyfyFjYxDQakQaA==]"
    storepassword: "![+yDkiDGqyfyFjYxDQakQaA==]"

#mule.vault.key: "czbc!B694tR@AX4!"
## Salesforce Config
salesforce:
  username: "![9Y3h6pu7PVSUD3b2CL+oSkwexjq2SNpcyzX30Z3AA5M=]"
  password: "![bjvhOnfjV51Rrv+Lm70/mQ==]"