### Environment specific non secure  properties go here ###


### API ID ### Create API Configuration in API Manager for DEV Env and update the id. 
api:
  id: "16652604"
 
json:
  logger:
    disabled:
      fields: ""


  

  

  